
export const sportsProduct = [
    {
        id: 1,
        category: "Протеины",
        name: "Whey Protein Isolate",
        brand: "Optimum Nutrition",
        price: 3200,
        weight: "900 г",
        flavor: "Ваниль",
        description: "Высококачественный изолят сывороточного белка для быстрого восстановления мышц после тренировок. Содержит минимальное количество углеводов и жиров, что делает его идеальным для спортсменов на сушке.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Ароматизатор ванили", "Сукралоза"],
        calories: 120,
        proteinPerServing: "25 г",
        carbsPerServing: "2 г",
        fatPerServing: "1 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну мерную ложку с 250 мл воды или молока после тренировки.",
        storageInstructions: "Хранить в сухом, прохладном месте.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_protein/img2.jpg')
      },
      {
        id: 2,
        category: "Протеины",
        name: "Casein Protein",
        brand: "MuscleTech",
        price: 2800,
        weight: "800 г",
        flavor: "Шоколад",
        description: "Медленно усваиваемый казеиновый протеин для ночного восстановления. Поддерживает мышцы и предотвращает катаболизм во время сна.",
        rating: 4.5,
        inStock: true,
        ingredients: ["Казеиновый белок", "Какао-порошок", "Сукралоза"],
        calories: 110,
        proteinPerServing: "24 г",
        carbsPerServing: "1 г",
        fatPerServing: "0.5 г",
        servingsPerContainer: 28,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Принимайте одну мерную ложку за 30 минут до сна.",
        storageInstructions: "Держите упаковку плотно закрытой в прохладном, сухом месте.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_protein/img2.jpg')
      },
      {
        id: 3,
        category: "Протеины",
        name: "Soy Protein",
        brand: "NOW Foods",
        price: 2500,
        weight: "700 г",
        flavor: "Клубника",
        description: "Соевый протеин для веганов. Обеспечивает полный набор аминокислот и подходит для тех, кто не переносит молочные продукты.",
        rating: 4.2,
        inStock: false,
        ingredients: ["Соевый белок", "Ароматизатор клубники", "Сукралоза"],
        calories: 130,
        proteinPerServing: "22 г",
        carbsPerServing: "3 г",
        fatPerServing: "1.5 г",
        servingsPerContainer: 25,
        manufacturerCountry: "Германия",
        shelfLife: "24 месяца",
        usage: "Смешайте с водой или растительным молоком после тренировки.",
        storageInstructions: "Храните в сухом месте вдали от прямых солнечных лучей.",
        allergenInfo: "Не содержит молочных продуктов.",
        imageUrl: require('../assets/images_protein/img2.jpg')
      },
      {
        id: 4,
        category: "Протеины",
        name: "Egg Protein",
        brand: "Dymatize",
        price: 2900,
        weight: "1 кг",
        flavor: "Безвкусный",
        description: "Яичный протеин с высокой биодоступностью. Подходит для людей с непереносимостью лактозы.",
        rating: 4.4,
        inStock: true,
        ingredients: ["Яичный белок", "Подсластитель"],
        calories: 140,
        proteinPerServing: "26 г",
        carbsPerServing: "1 г",
        fatPerServing: "0 г",
        servingsPerContainer: 35,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Добавляйте в выпечку или коктейли.",
        storageInstructions: "Хранить в плотно закрытой упаковке.",
        allergenInfo: "Содержит яйца.",
        imageUrl: require('../assets/images_protein/img2.jpg')
      },
      {
        id: 5,
        category: "Протеины",
        name: "Hydrolyzed Whey Protein",
        brand: "BSN",
        price: 3100,
        weight: "850 г",
        flavor: "Малина",
        description: "Гидролизат сывороточного белка для быстрого усвоения и поддержки мышц.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Гидролизованный сывороточный белок", "Ароматизатор малины"],
        calories: 100,
        proteinPerServing: "27 г",
        carbsPerServing: "1 г",
        fatPerServing: "0.5 г",
        servingsPerContainer: 32,
        manufacturerCountry: "Канада",
        shelfLife: "24 месяца",
        usage: "Идеально после тренировок или между приемами пищи.",
        storageInstructions: "Держите упаковку закрытой.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_protein/img2.jpg')
      },
      {
        id: 6,
        category: "Протеины",
        name: "Organic Plant Protein",
        brand: "Garden of Life",
        price: 3300,
        weight: "750 г",
        flavor: "Шоколад",
        description: "Органический растительный протеин с добавлением витаминов и минералов. Подходит для веганов.",
        rating: 4.6,
        inStock: true,
        ingredients: ["Гороховый протеин", "Конопляный белок", "Какао"],
        calories: 150,
        proteinPerServing: "21 г",
        carbsPerServing: "4 г",
        fatPerServing: "2 г",
        servingsPerContainer: 20,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте с миндальным молоком для лучшего вкуса.",
        storageInstructions: "Хранить в прохладном месте.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_protein/img5.jpg')
      },
      {
        id: 7,
        category: "Протеины",
        name: "Beef Protein Isolate",
        brand: "Carnivor",
        price: 3400,
        weight: "900 г",
        flavor: "Карамель",
        description: "Изолят говяжьего протеина с уникальным аминокислотным профилем. Отличный источник белка для роста мышц.",
        rating: 4.3,
        inStock: true,
        ingredients: ["Говяжий протеин", "Ароматизатор карамели"],
        calories: 110,
        proteinPerServing: "23 г",
        carbsPerServing: "1.5 г",
        fatPerServing: "0 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Идеально до или после тренировки.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Без аллергенов.",
        imageUrl: require('../assets/images_protein/img5.jpg')
      },
      {
        id: 8,
        category: "Протеины",
        name: "Multi-Source Protein",
        brand: "Vega",
        price: 3500,
        weight: "1 кг",
        flavor: "Ваниль",
        description: "Смесь растительных белков для максимального усвоения. Подходит для всех, включая веганов.",
        rating: 4.5,
        inStock: false,
        ingredients: ["Гороховый белок", "Чиа", "Киноа"],
        calories: 160,
        proteinPerServing: "20 г",
        carbsPerServing: "6 г",
        fatPerServing: "3 г",
        servingsPerContainer: 25,
        manufacturerCountry: "Канада",
        shelfLife: "24 месяца",
        usage: "Добавляйте в коктейли или каши.",
        storageInstructions: "Хранить в прохладном месте.",
        allergenInfo: "Без аллергенов.",
        imageUrl: require('../assets/images_protein/img5.jpg')
      },
      {
        id: 9,
        category: "Протеины",
        name: "Milk Protein",
        brand: "MyProtein",
        price: 2600,
        weight: "1.2 кг",
        flavor: "Банан",
        description: "Молочный протеин для медленного усвоения. Отлично подходит для употребления в течение дня.",
        rating: 4.4,
        inStock: true,
        ingredients: ["Молочный белок", "Ароматизатор банана"],
        calories: 140,
        proteinPerServing: "25 г",
        carbsPerServing: "3 г",
        fatPerServing: "1.5 г",
        servingsPerContainer: 40,
        manufacturerCountry: "Великобритания",
        shelfLife: "18 месяцев",
        usage: "Принимайте с молоком для лучшего вкуса.",
        storageInstructions: "Хранить в прохладном месте.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_protein/img5.jpg')
      },
      {
        id: 10,
        category: "Протеины",
        name: "Premium Whey Blend",
        brand: "Rule 1",
        price: 3000,
        weight: "900 г",
        flavor: "Кокос",
        description: "Смесь концентрата и изолята сывороточного белка для комплексной поддержки.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Ароматизатор кокоса"],
        calories: 120,
        proteinPerServing: "24 г",
        carbsPerServing: "2 г",
        fatPerServing: "1 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте с водой или молоком после тренировки.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_protein/img5.jpg')
      },
      {
        id: 11,
        category: "Креатины",
        name: "Creatine Monohydrate",
        brand: "Optimum Nutrition",
        price: 2200,
        weight: "300 г",
        flavor: "Безвкусный",
        description: "Чистый креатин моногидрат, повышающий физическую выносливость и силу. Это один из самых популярных и эффективных креатинов на рынке.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Креатин моногидрат"],
        calories: 0,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 60,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну мерную ложку (5 г) с водой или соком и принимайте перед тренировкой или после.",
        storageInstructions: "Хранить в сухом, прохладном месте, вдали от прямых солнечных лучей.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 12,
        category: "Креатины",
        name: "Creatine HCl",
        brand: "Kre-Alkalyn",
        price: 2500,
        weight: "120 капсул",
        flavor: "Безвкусный",
        description: "Ультрачистый креатин HCl с высокой усвояемостью. Не вызывает задержки воды и не имеет побочных эффектов.",
        rating: 4.6,
        inStock: true,
        ingredients: ["Креатин гидрохлорид"],
        calories: 0,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 40,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Принимайте 3 капсулы в день до или после тренировки.",
        storageInstructions: "Хранить в сухом, прохладном месте.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 13,
        category: "Креатины",
        name: "Creatine Ethyl Ester",
        brand: "MuscleTech",
        price: 2700,
        weight: "150 г",
        flavor: "Лимон",
        description: "Креатин этиловый эфир, который помогает ускорить восстановление и увеличить силовые показатели при интенсивных тренировках.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Креатин этиловый эфир", "Ароматизатор лимона"],
        calories: 10,
        proteinPerServing: "0 г",
        carbsPerServing: "2 г",
        fatPerServing: "0 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну мерную ложку с водой или соком. Принимайте за 20 минут до тренировки.",
        storageInstructions: "Хранить в сухом месте, вдали от прямых солнечных лучей.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 14,
        category: "Креатины",
        name: "Creatine Kre-Alkalyn",
        brand: "Evlution Nutrition",
        price: 2200,
        weight: "300 г",
        flavor: "Безвкусный",
        description: "Запатентованный креатин Kre-Alkalyn с улучшенной усвояемостью и без побочных эффектов. Позволяет значительно повысить интенсивность тренировок.",
        rating: 4.5,
        inStock: true,
        ingredients: ["Креатин Kre-Alkalyn"],
        calories: 0,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 60,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Принимайте одну порцию (1 капсулу) в день перед тренировкой.",
        storageInstructions: "Хранить в прохладном месте, вдали от детей.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 15,
        category: "Креатины",
        name: "CreaPure Creatine",
        brand: "German Nutrition",
        price: 2800,
        weight: "500 г",
        flavor: "Безвкусный",
        description: "CreaPure – это высококачественный креатин моногидрат, произведенный в Германии. Обеспечивает отличную усвояемость и эффективное повышение физических показателей.",
        rating: 4.9,
        inStock: true,
        ingredients: ["Креатин моногидрат"],
        calories: 0,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 100,
        manufacturerCountry: "Германия",
        shelfLife: "36 месяцев",
        usage: "Смешайте 5 г с водой или соком и принимайте до или после тренировки.",
        storageInstructions: "Хранить в сухом месте, вдали от влаги.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 16,
        category: "Креатины",
        name: "Kreatin Monohydrat",
        brand: "Weider",
        price: 2300,
        weight: "500 г",
        flavor: "Безвкусный",
        description: "Креатин моногидрат от Weider, стимулирующий рост мышечной массы и силы. Подходит для всех типов тренингов.",
        rating: 4.6,
        inStock: true,
        ingredients: ["Креатин моногидрат"],
        calories: 0,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 100,
        manufacturerCountry: "Германия",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию (5 г) с водой или соком и принимайте перед или после тренировки.",
        storageInstructions: "Хранить в сухом месте, при температуре не более 25°C.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 17,
        category: "Креатины",
        name: "Creatine MagnaPower",
        brand: "MusclePharm",
        price: 2900,
        weight: "300 г",
        flavor: "Безвкусный",
        description: "Креатин MagnaPower — это улучшенная форма креатина, которая быстрее усваивается организмом и обладает высокой эффективностью.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Креатин магнезий", "Креатин моногидрат"],
        calories: 5,
        proteinPerServing: "0 г",
        carbsPerServing: "1 г",
        fatPerServing: "0 г",
        servingsPerContainer: 60,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте 5 г с водой или соком и принимайте перед тренировкой.",
        storageInstructions: "Хранить в сухом месте, вдали от солнечных лучей.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 18,
        category: "Креатины",
        name: "Creapure",
        brand: "German Supplements",
        price: 3100,
        weight: "500 г",
        flavor: "Безвкусный",
        description: "Премиум креатин моногидрат Creapure. Это чистейшая форма креатина, произведенная в Германии, гарантированно не имеет примесей и побочных эффектов.",
        rating: 4.9,
        inStock: true,
        ingredients: ["Креатин моногидрат"],
        calories: 0,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 100,
        manufacturerCountry: "Германия",
        shelfLife: "36 месяцев",
        usage: "Принимайте 5 г с водой или соком перед тренировкой.",
        storageInstructions: "Хранить в сухом, темном месте, при температуре не выше 25°C.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 19,
        category: "Креатины",
        name: "Kreatin Plus",
        brand: "Fitness Authority",
        price: 2400,
        weight: "300 г",
        flavor: "Лимон",
        description: "Эффективная добавка для увеличения силы и выносливости. Отличается хорошей усвояемостью и качественными ингредиентами.",
        rating: 4.5,
        inStock: true,
        ingredients: ["Креатин моногидрат", "Ароматизатор лимона"],
        calories: 10,
        proteinPerServing: "0 г",
        carbsPerServing: "2 г",
        fatPerServing: "0 г",
        servingsPerContainer: 60,
        manufacturerCountry: "Польша",
        shelfLife: "24 месяца",
        usage: "Принимайте 5 г с водой или соком перед тренировкой.",
        storageInstructions: "Хранить в сухом месте, вдали от детей.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
      },
      {
        id: 20,
        category: "Креатины",
        name: "Kreatin Extreme",
        brand: "BSN",
        price: 3300,
        weight: "600 г",
        flavor: "Ягодный микс",
        description: "Ультраэффективный креатин, который способствует увеличению силы, выносливости и мышечной массы.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Креатин моногидрат", "Ароматизатор ягодного микса"],
        calories: 15,
        proteinPerServing: "0 г",
        carbsPerServing: "3 г",
        fatPerServing: "0 г",
        servingsPerContainer: 80,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну порцию с водой или соком и принимайте до или после тренировки.",
        storageInstructions: "Хранить в сухом месте, вдали от прямых солнечных лучей.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_creatine/img8.jpg'),
       },
       {
        id: 21,
        category: "Гейнеры",
        name: "Mass Gainer",
        brand: "Optimum Nutrition",
        price: 3500,
        weight: "2.27 кг",
        flavor: "Шоколад",
        description: "Высококалорийный гейнер для быстрого набора массы. Содержит углеводы с низким гликемическим индексом, что способствует стабилизации уровня сахара в крови.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Углеводы", "Сывороточный протеин", "Мальтодекстрин", "Какао"],
        calories: 1250,
        proteinPerServing: "50 г",
        carbsPerServing: "250 г",
        fatPerServing: "6 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте 2 мерные ложки с 400-500 мл воды или молока. Принимайте 1-2 раза в день.",
        storageInstructions: "Хранить в сухом, прохладном месте, вдали от солнечных лучей.",
        allergenInfo: "Содержит молочные продукты, соя.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 22,
        category: "Гейнеры",
        name: "Mass Tech",
        brand: "MuscleTech",
        price: 4200,
        weight: "2.27 кг",
        flavor: "Ваниль",
        description: "Мощный гейнер для спортсменов, стремящихся к быстрому набору массы. Содержит аминокислоты, протеины и углеводы для ускоренного восстановления.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Мальтодекстрин", "Аминокислоты"],
        calories: 1300,
        proteinPerServing: "63 г",
        carbsPerServing: "250 г",
        fatPerServing: "8 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию (2 мерные ложки) с 400-500 мл воды или молока.",
        storageInstructions: "Хранить в сухом, темном месте, вдали от детей.",
        allergenInfo: "Содержит молочные продукты и соевые компоненты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 23,
        category: "Гейнеры",
        name: "Serious Mass",
        brand: "Optimum Nutrition",
        price: 4000,
        weight: "2.72 кг",
        flavor: "Клубника",
        description: "Один из самых популярных гейнеров для набора массы. Обеспечивает спортсмена необходимыми калориями и макроэлементами.",
        rating: 4.9,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Мальтодекстрин", "Фрукты", "Какао"],
        calories: 1250,
        proteinPerServing: "50 г",
        carbsPerServing: "254 г",
        fatPerServing: "4 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте 2 мерные ложки с 400-500 мл молока или воды.",
        storageInstructions: "Хранить в сухом, прохладном месте.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 24,
        category: "Гейнеры",
        name: "True Mass",
        brand: "BSN",
        price: 3700,
        weight: "1.81 кг",
        flavor: "Шоколадный пирог",
        description: "Гейнер с улучшенной формулой для быстрого восстановления после тренировки и роста мышечной массы. Включает витамины и минералы для полноценного питания.",
        rating: 4.6,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Кокосовое молоко", "Мальтодекстрин"],
        calories: 700,
        proteinPerServing: "46 г",
        carbsPerServing: "90 г",
        fatPerServing: "16 г",
        servingsPerContainer: 26,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну порцию с 350-450 мл воды или молока.",
        storageInstructions: "Хранить в сухом, прохладном месте, вдали от прямых солнечных лучей.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 25,
        category: "Гейнеры",
        name: "Gainer XL",
        brand: "Universal Nutrition",
        price: 3900,
        weight: "3.2 кг",
        flavor: "Трюфель",
        description: "Мощный гейнер для активных спортсменов, стремящихся набрать массу и улучшить результаты в тренировках. Содержит протеин с высоким содержанием аминокислот.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Яичный белок", "Мальтодекстрин"],
        calories: 1150,
        proteinPerServing: "60 г",
        carbsPerServing: "215 г",
        fatPerServing: "8 г",
        servingsPerContainer: 25,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Принимайте одну порцию (2 мерные ложки) с 400 мл воды или молока.",
        storageInstructions: "Хранить в прохладном, сухом месте.",
        allergenInfo: "Содержит молочные и яичные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 26,
        category: "Гейнеры",
        name: "Gainer Pro",
        brand: "Body Attack",
        price: 4300,
        weight: "2.5 кг",
        flavor: "Ягоды",
        description: "Ультраконцентрированный гейнер, специально разработанный для быстрого набора мышечной массы. Включает комплекс витаминов и минералов для улучшения усвоения.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Молочный протеин", "Мальтодекстрин", "Глюкоза", "Ягодный экстракт"],
        calories: 1200,
        proteinPerServing: "40 г",
        carbsPerServing: "250 г",
        fatPerServing: "5 г",
        servingsPerContainer: 30,
        manufacturerCountry: "Германия",
        shelfLife: "24 месяца",
        usage: "Смешайте 2 мерные ложки с 300-400 мл воды или молока.",
        storageInstructions: "Хранить в сухом месте, при температуре не выше 25°C.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 27,
        category: "Гейнеры",
        name: "Mass Gainer Premium",
        brand: "Scitec Nutrition",
        price: 4600,
        weight: "2.5 кг",
        flavor: "Клубника-ваниль",
        description: "Премиум гейнер для интенсивного набора массы и улучшения спортивных результатов. Включает углеводы с низким гликемическим индексом и полноценный набор витаминов.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Глюкоза", "Аминокислоты"],
        calories: 1300,
        proteinPerServing: "50 г",
        carbsPerServing: "250 г",
        fatPerServing: "6 г",
        servingsPerContainer: 50,
        manufacturerCountry: "Венгрия",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 400-500 мл молока или воды.",
        storageInstructions: "Хранить в сухом месте, вдали от влаги.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 28,
        category: "Гейнеры",
        name: "Super Mass Gainer",
        brand: "Dymatize",
        price: 4200,
        weight: "2.27 кг",
        flavor: "Шоколад",
        description: "Гейнер для спортсменов, нуждающихся в быстром наборе массы. Содержит протеин, углеводы и витамины для ускоренного восстановления и роста мышц.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Мальтодекстрин", "Витамины"],
        calories: 1300,
        proteinPerServing: "52 г",
        carbsPerServing: "252 г",
        fatPerServing: "4 г",
        servingsPerContainer: 20,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну порцию с 400 мл воды или молока.",
        storageInstructions: "Хранить в сухом месте, вдали от солнечных лучей.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 29,
        category: "Гейнеры",
        name: "Mega Mass",
        brand: "Weider",
        price: 3800,
        weight: "2.72 кг",
        flavor: "Тропический микс",
        description: "Гейнер с богатым составом, идеален для быстрого набора массы и поддержания энергии в течение всего дня.",
        rating: 4.6,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Тропический экстракт", "Мальтодекстрин"],
        calories: 1200,
        proteinPerServing: "50 г",
        carbsPerServing: "220 г",
        fatPerServing: "8 г",
        servingsPerContainer: 25,
        manufacturerCountry: "Германия",
        shelfLife: "18 месяцев",
        usage: "Принимайте одну порцию с 400-500 мл воды или молока.",
        storageInstructions: "Хранить в сухом месте, вдалеке от влаги.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 30,
        category: "Гейнеры",
        name: "Giant Mass",
        brand: "Scitec Nutrition",
        price: 5000,
        weight: "3.5 кг",
        flavor: "Шоколад",
        description: "Идеальный гейнер для набора массы с высокой калорийностью и богатым содержанием углеводов и белков.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Сывороточный протеин", "Мальтодекстрин", "Витамины"],
        calories: 1400,
        proteinPerServing: "60 г",
        carbsPerServing: "280 г",
        fatPerServing: "10 г",
        servingsPerContainer: 25,
        manufacturerCountry: "Венгрия",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 500 мл воды или молока.",
        storageInstructions: "Хранить в сухом месте, при температуре не выше 25°C.",
        allergenInfo: "Содержит молочные продукты.",
        imageUrl: require('../assets/images_gainer/img3.jpg'),
      },
      {
        id: 31,
        category: "Аминокислоты",
        name: "BCAA 2:1:1",
        brand: "Scitec Nutrition",
        price: 2500,
        weight: "500 г",
        flavor: "Вишня",
        description: "Эффективный комплекс аминокислот BCAA в соотношении 2:1:1 для улучшения восстановления и роста мышц.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Лейцин", "Изолейцин", "Валин"],
        calories: 50,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 50,
        manufacturerCountry: "Венгрия",
        shelfLife: "24 месяца",
        usage: "Размешайте одну порцию с 300 мл воды и принимайте до или после тренировки.",
        storageInstructions: "Хранить в сухом месте, при температуре не выше 25°C.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 32,
        category: "Аминокислоты",
        name: "Amino 8000",
        brand: "Universal Nutrition",
        price: 3200,
        weight: "750 г",
        flavor: "Лимон",
        description: "Комплекс аминокислот для активных тренировок, быстро восстанавливает мышцы и снижает утомляемость.",
        rating: 4.6,
        inStock: true,
        ingredients: ["L-Лейцин", "L-Глутамин", "L-Цистеин"],
        calories: 40,
        proteinPerServing: "10 г",
        carbsPerServing: "2 г",
        fatPerServing: "0 г",
        servingsPerContainer: 75,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Принимайте одну порцию с 250 мл воды перед тренировкой.",
        storageInstructions: "Хранить в прохладном, сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 33,
        category: "Аминокислоты",
        name: "Essential Amino Energy",
        brand: "Optimum Nutrition",
        price: 2700,
        weight: "275 г",
        flavor: "Апельсин",
        description: "Смешанные аминокислоты и кофеин для улучшения энергии, выносливости и восстановления мышц.",
        rating: 4.5,
        inStock: true,
        ingredients: ["L-Лейцин", "L-Глутамин", "Кофеин"],
        calories: 100,
        proteinPerServing: "5 г",
        carbsPerServing: "5 г",
        fatPerServing: "0 г",
        servingsPerContainer: 55,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну порцию с 200 мл воды и принимайте перед тренировкой.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 34,
        category: "Аминокислоты",
        name: "Amino X",
        brand: "BSN",
        price: 3300,
        weight: "465 г",
        flavor: "Лимонная сода",
        description: "Мощный комплекс аминокислот для улучшения восстановления и сокращения времени между тренировками.",
        rating: 4.7,
        inStock: true,
        ingredients: ["L-Глутамин", "L-Лейцин", "Аминокислотный комплекс"],
        calories: 70,
        proteinPerServing: "10 г",
        carbsPerServing: "5 г",
        fatPerServing: "0 г",
        servingsPerContainer: 50,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 250 мл воды после тренировки.",
        storageInstructions: "Хранить в сухом месте, вдали от солнечных лучей.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 35,
        category: "Аминокислоты",
        name: "Amino Build",
        brand: "MuscleTech",
        price: 2900,
        weight: "420 г",
        flavor: "Лимонный лайм",
        description: "Силовая аминокислота для увеличения выносливости и силы в тренировках, улучшает восстановление мышц.",
        rating: 4.8,
        inStock: true,
        ingredients: ["L-Лейцин", "L-Цистеин", "Витамины"],
        calories: 80,
        proteinPerServing: "5 г",
        carbsPerServing: "10 г",
        fatPerServing: "0 г",
        servingsPerContainer: 40,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 200 мл воды до тренировки.",
        storageInstructions: "Хранить в сухом месте, вдали от влаги.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 36,
        category: "Аминокислоты",
        name: "Amino Acid Complex",
        brand: "Dymatize",
        price: 3100,
        weight: "500 г",
        flavor: "Тропики",
        description: "Комплекс аминокислот для улучшения процесса восстановления, повышения силы и выносливости.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Лейцин", "Изолейцин", "Глутамин"],
        calories: 60,
        proteinPerServing: "6 г",
        carbsPerServing: "4 г",
        fatPerServing: "1 г",
        servingsPerContainer: 50,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну порцию с 250 мл воды или сока и принимайте до или после тренировки.",
        storageInstructions: "Хранить в прохладном, сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 37,
        category: "Аминокислоты",
        name: "Amino Stack",
        brand: "Kaged Muscle",
        price: 3400,
        weight: "400 г",
        flavor: "Ягоды",
        description: "Амега аминокислот для максимальной стимуляции анаболизма и восстановления после тренировки.",
        rating: 4.8,
        inStock: true,
        ingredients: ["BCAA", "L-Глутамин", "L-Аргинин"],
        calories: 50,
        proteinPerServing: "5 г",
        carbsPerServing: "3 г",
        fatPerServing: "0 г",
        servingsPerContainer: 40,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Размешайте одну порцию в 250 мл воды и принимайте после тренировки.",
        storageInstructions: "Хранить в сухом месте, при температуре не выше 25°C.",
        allergenInfo: "Не содержит аллергенов.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 38,
        category: "Аминокислоты",
        name: "Amino Pro",
        brand: "Cellucor",
        price: 3500,
        weight: "400 г",
        flavor: "Арбуз",
        description: "Протеиновый комплекс аминокислот с электролитами для восстановления и предотвращения деградации мышечной ткани.",
        rating: 4.6,
        inStock: true,
        ingredients: ["BCAA", "L-Лейцин", "L-Глутамин", "Электролиты"],
        calories: 40,
        proteinPerServing: "5 г",
        carbsPerServing: "3 г",
        fatPerServing: "0 г",
        servingsPerContainer: 40,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Размешайте одну порцию в 250 мл воды до тренировки.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 39,
        category: "Аминокислоты",
        name: "BCAA 5000",
        brand: "Evlution Nutrition",
        price: 2600,
        weight: "300 г",
        flavor: "Клубника-Лайм",
        description: "BCAA с добавлением витаминов для улучшения восстановления и роста мышечной массы.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Лейцин", "Изолейцин", "Валин", "Витамины B"],
        calories: 60,
        proteinPerServing: "0 г",
        carbsPerServing: "0 г",
        fatPerServing: "0 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 200 мл воды перед или после тренировки.",
        storageInstructions: "Хранить в прохладном месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 40,
        category: "Аминокислоты",
        name: "Instantized BCAA",
        brand: "Dymatize",
        price: 3100,
        weight: "500 г",
        flavor: "Арбуз",
        description: "Идеальный продукт для ускоренного восстановления после интенсивных тренировок и повышения силы.",
        rating: 4.9,
        inStock: true,
        ingredients: ["Лейцин", "Изолейцин", "Валин"],
        calories: 50,
        proteinPerServing: "5 г",
        carbsPerServing: "2 г",
        fatPerServing: "0 г",
        servingsPerContainer: 50,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 250 мл воды и принимайте во время тренировки.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_amino/img5.jpg'),
      },
      {
        id: 41,
        category: "Предтренировочные-комплексы",
        name: "C4 Original",
        brand: "Cellucor",
        price: 2200,
        weight: "195 г",
        flavor: "Арбуз",
        description: "Мощный предтренировочный комплекс для повышения энергии, силы и выносливости в тренировках.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Кофеин", "Бета-аланин", "Аргинин"],
        calories: 50,
        proteinPerServing: "0 г",
        carbsPerServing: "3 г",
        fatPerServing: "0 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 200 мл воды за 30 минут до тренировки.",
        storageInstructions: "Хранить в сухом, прохладном месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_preworkout/img3.jpg'),
      },
      {
        id: 42,
        category: "Предтренировочные-комплексы",
        name: "Pre-Kaged",
        brand: "Kaged Muscle",
        price: 3900,
        weight: "312 г",
        flavor: "Цитрусовая взрывная смесь",
        description: "Передовой предтренировочный комплекс с добавлением витаминов и электролитов для улучшения концентрации и выносливости.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Бета-аланин", "Кофеин", "Л-карнитин"],
        calories: 60,
        proteinPerServing: "0 г",
        carbsPerServing: "5 г",
        fatPerServing: "0 г",
        servingsPerContainer: 40,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 300 мл воды за 30 минут до тренировки.",
        storageInstructions: "Хранить в прохладном месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_preworkout/img3.jpg'),
      },
      {
        id: 43,
        category: "Предтренировочные-комплексы",
        name: "Pre-Workout Explosion",
        brand: "MuscleTech",
        price: 3500,
        weight: "300 г",
        flavor: "Лимонная кислота",
        description: "Предтренировочный комплекс с сильным стимулятором для высокой концентрации и энергии.",
        rating: 4.6,
        inStock: true,
        ingredients: ["Креатин", "Кофеин", "Бета-аланин"],
        calories: 50,
        proteinPerServing: "0 г",
        carbsPerServing: "4 г",
        fatPerServing: "0 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "18 месяцев",
        usage: "Смешайте одну порцию с 200 мл воды за 20 минут до тренировки.",
        storageInstructions: "Хранить в сухом, прохладном месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_preworkout/img3.jpg'),
      },
      {
        id: 44,
        category: "Предтренировочные-комплексы",
        name: "N.O.-Xplode",
        brand: "BSN",
        price: 3000,
        weight: "500 г",
        flavor: "Апельсин",
        description: "Популярный предтренировочный комплекс с энергией, улучшением кровотока и фокусом на тренировки.",
        rating: 4.7,
        inStock: true,
        ingredients: ["Кофеин", "Л-Цитруллин", "Бета-аланин"],
        calories: 60,
        proteinPerServing: "0 г",
        carbsPerServing: "5 г",
        fatPerServing: "0 г",
        servingsPerContainer: 50,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 250 мл воды за 20-30 минут до тренировки.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_preworkout/img3.jpg'),
      },
      {
        id: 45,
        category: "Предтренировочные-комплексы",
        name: "Gold Standard Pre-Workout",
        brand: "Optimum Nutrition",
        price: 3300,
        weight: "300 г",
        flavor: "Зеленый яблоко",
        description: "Предтренировочный комплекс с улучшенной формулой для высокой выносливости и энергетического всплеска.",
        rating: 4.8,
        inStock: true,
        ingredients: ["Кофеин", "Бета-аланин", "Цитруллин"],
        calories: 40,
        proteinPerServing: "0 г",
        carbsPerServing: "4 г",
        fatPerServing: "0 г",
        servingsPerContainer: 30,
        manufacturerCountry: "США",
        shelfLife: "24 месяца",
        usage: "Смешайте одну порцию с 250 мл воды за 20-30 минут до тренировки.",
        storageInstructions: "Хранить в сухом месте.",
        allergenInfo: "Не содержит молочные продукты.",
        imageUrl: require('../assets/images_preworkout/img3.jpg'),
      }
];